# **Step-1** :
## Import Libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# **Step-2** :
## Import Your Data

In [3]:
df = pd.read_csv('Advertising.csv')
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

### Removed Unnecessary Column

In [4]:
df = df.drop(['Unnamed: 0'], axis=1)
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

# **Step-3**
## Split Data ( x , y )

In [5]:
x = df[['TV', 'radio', 'newspaper']]
y = df[['sales']]

In [6]:
x.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [7]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

## Import Libraries and Split Data

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# **Step-4**
## Create and Fit your Model

In [9]:
model = LinearRegression().fit(x_train, y_train)
model

LinearRegression()

In [10]:
# i1 , i2, i3
model.coef_

array([[ 0.04458402,  0.19649703, -0.00278146]])

In [11]:
model.intercept_

array([2.99489303])

# **Step-5**
## Prediction

In [12]:
model.predict([[44.5, 39.3, 45.1]])

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[12.57577134]])

## Plotting

In [13]:
x_surf, y_surf = np.meshgrid(np.linspace(df.TV.min(), df.TV.max(), 100),np.linspace(df.radio.min(), df.radio.max(), 100))
onlyx = pd.DataFrame({'TV': x_surf.ravel(), 'radio': y_surf.ravel()})

In [14]:
x_surf, y_surf = np.meshgrid(np.linspace(df.TV.min(), df.TV.max(), 100),np.linspace(df.radio.min(), df.radio.max(), 100))
onlyX = pd.DataFrame({'TV': x_surf.ravel(), 'radio': y_surf.ravel()})

In [15]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(df['TV'],df['newspaper'],df['sales'],c='red', marker='o', alpha=0.5)
ax.set_xlabel('TV')
ax.set_ylabel('newspaper')
ax.set_zlabel('sales')
plt.show()

NameError: name 'plt' is not defined

In [ ]:
# How to plot multiple linear regression model ?
# How to test the eficacy of model ?